pygments: true
lsi: false
paginate:
permalink: /:categories/:title/
root_uri: http://plugfr.org
timezone: Europe/Paris
include:
  - .htaccess
exclude:
  - bin
  - script
  - README.markdown
  - public
  - vendor
  - bundle
  - Gemfile
  - Gemfile.lock
  - plugfr.org.tmproj
