auto: true
pygments: true
lsi: false
paginate:
permalink: /:categories/:title/
root_uri: http://plugfr.org
include:
  - .htaccess
exclude:
  - script
  - README.markdown
  - public
  - plugfr.org.tmproj
